### ISSUE TITLE
Porting tidy() methods for metafor objects to broom

### ISSUE THREAD

**Issue by alexpghayes** [malcolmbarrett/tidymeta#2]
People have been asking for these for a while but I haven't implemented them yet! Would you be willing to contribute your code to `broom`!?

**Comment by malcolmbarrett** [comment]
Yes, definitely. I started this project before it was clear what direction broom was going to go in with all the many models it supported, so I had always thought that might be a possibility. Also going to tag @softloud since this project has been on pause while we look for time to collab

**Comment by softloud** [comment]
We so need to get to this - especially with [ESH2](https://evidencesynthesishackathon.com/) coming up. Don't know if either of you are coming?! Anyways, we'll be working on a `metaverse::` metapackage there of tidy meta-analysis functions. I can take ideas to the team.

I needed _something_ for my [simulation](https://github.com/softloud/metasim) package, so I've been using my [crap bespoke functions](https://github.com/softloud/metabroom).

**Comment by malcolmbarrett** [comment]
Can you tell us more about that project? Would it be better to port these functions (or merge with yours in metabroom) to metaverse? (is this taking over what we had in mind for metameta?) Depending on the scope of metaverse, it might be better to be a stand-alone package like broom.mixed or otherwise a spot to collaborate on these methods a bit before porting to broom proper? 

tidymeta has been working for quite a while, and I set it aside for the sake of collaborating, so it would be nice to put at least parts of it somewhere!

I'm deeply jealous, but I'm afraid that event is a tad far for me ✈️

**Comment by softloud** [comment]
Alas, we'll miss you! Well, the opportune time would be now, @malcolmbarrett, to finish this. But I saw you just got married?! People are very keen to have broom functionality at ESH. Will you have any time before April 8? 

I'm working remotely and have my simulations under control, so can accommodate any time that works for you.

**Comment by malcolmbarrett** [comment]
I can work on this next week! Let's compare notes offline in the meantime. Looking at metabroom and tidymeta again, I don't think basic coverage for metafor will be a challenge at all

**Comment by softloud** [comment]
Excellent are you on the openevisynth slack? If not I can shoot you an invite. Let's do this! This will be an awesome thing to wrap up before ESH, 'cause then they can make use of it for all the proposed projects. 
***
Update - you're there. I've set up a channel so we can drop thoughts and whatnot.

**Comment by malcolmbarrett** [comment]
FYI @alexpghayes, we're working on this over at [metabroom](https://github.com/softloud/metabroom). We're making sure it works with most of the many, many models in metafor but will port to a proper broom PR thereafter
